// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Pooled connection used by Prisma Client at runtime
    url: env("DATABASE_URL"),
    // Direct connection used by Prisma Migrate/Introspection
    directUrl: env("DIRECT_URL"),
  },
});
